jenkinsdata:
    image: ashishbhatt12/data-volume-container
    build: jenkins-data
jenkinsmaster:
    image: ashishbhatt12/jenkins-master
    build: jenkins-master
    volumes_from: 
        - jenkinsdata
    ports:
        - "8080:8080"
    command: 
        java -jar /usr/share/jenkins/jenkins.war