FROM jenkinsci/jenkins:latest
MAINTAINER Ashish Bhatt

# COPY plugins.txt /plugins.txt
# RUN /usr/local/bin/plugins.sh plugins.txt

# Create Jenkins log file
USER root
RUN mkdir /var/log/jenkins
RUN mkdir /var/cache/jenkins
RUN chown -R jenkins:jenkins /var/log/jenkins
RUN chown -R jenkins:jenkins /var/cache/jenkins
USER jenkins

# Set default options
ENV JAVA_OPTS="-Xmx8192m"
ENV JENKINS_OPTS="--handlerCountStartup=100 --handlerCountMax=300 --logfile=/var/log/jenkins/jenkins.log --webroot=/var/cache/jenkins/war"